# -*- coding: utf-8 -*-
"""Counting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C2JxvpR1hMYURyaNcXcoHnBqT1sUh2m0
"""

scores = input().split()
scores = [int(x) for x in scores]
fail_count = sum(1 for s in scores if s < 60)
print(fail_count)